-- ATSV Fanseite – Tippspiel
-- Einmalig im Supabase SQL Editor ausführen.

create table if not exists public.tippspiel_tipps (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  name text not null,
  match_id text not null,
  home_team text not null,
  away_team text not null,
  tip_home integer not null check (tip_home >= 0 and tip_home <= 99),
  tip_away integer not null check (tip_away >= 0 and tip_away <= 99),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (participant_id, match_id)
);

alter table public.tippspiel_tipps enable row level security;

drop policy if exists "tippspiel select" on public.tippspiel_tipps;
create policy "tippspiel select"
on public.tippspiel_tipps for select
to anon, authenticated
using (true);

drop policy if exists "tippspiel insert" on public.tippspiel_tipps;
create policy "tippspiel insert"
on public.tippspiel_tipps for insert
to anon, authenticated
with check (length(trim(name)) between 2 and 30 and length(trim(participant_id)) >= 20);

drop policy if exists "tippspiel update" on public.tippspiel_tipps;
create policy "tippspiel update"
on public.tippspiel_tipps for update
to anon, authenticated
using (length(trim(participant_id)) >= 20)
with check (length(trim(name)) between 2 and 30 and length(trim(participant_id)) >= 20);

grant select, insert, update on public.tippspiel_tipps to anon, authenticated;
